package TMS;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class Teste20Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver","C:\\Users\\10097\\git\\Cervello-Automacao\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void teste20() throws InterruptedException {
	  driver.get("http://10.254.16.80/17042019-v2018/");
	    driver.findElement(By.id("login")).sendKeys("cervello");
	    driver.findElement(By.id("senha")).sendKeys("cervello01");
	    driver.findElement(By.xpath("//*[@id=\"frmLogin\"]/button")).click();
	   // Util.tempo(4);
	    driver.findElement(By.xpath("//*[@id=\"frmLogin\"]/button")).click();
    driver.manage().window().setSize(new Dimension(1696, 1026));
    vars.put("window_handles", driver.getWindowHandles());
    
    //Seleciona card no portal
    driver.findElement(By.xpath("//*[@id=\"portal\"]/main/div[1]/section/div[2]/ul/li[5]/div/a/p")).click();
    Thread.sleep(3000);
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector(".fancybox-item")).click();
    Thread.sleep(3000);
    driver.findElement(By.id("txtUsuario")).click();
    driver.switchTo().frame(1);
    Thread.sleep(3000);
    driver.findElement(By.id("txtlogin")).click();
    Thread.sleep(3000);
    // Seleciona o usuario
    driver.findElement(By.id("txtlogin")).sendKeys("cervello");
    Thread.sleep(3000);
    driver.findElement(By.id("peslogin")).click();
    Thread.sleep(3000);
    driver.findElement(By.id("lblSair")).click();
    Thread.sleep(3000);
    driver.switchTo().frame(0);
    Thread.sleep(3000);
    driver.findElement(By.cssSelector(".fancybox-item")).click();
    Thread.sleep(3000);
    driver.findElement(By.id("txtProjeto")).click();
    
    driver.switchTo().frame(0);
   
    {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = 'Estoque']")).click();
      }
       

    
   
    driver.switchTo().frame(1);
    {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = 'Ajuste']")).click();
      }
      driver.findElement(By.cssSelector("option:nth-child(8)")).click();
     // driver.findElement(By.cssSelector("option:nth-child(8)")).click();
      {
        WebElement element = driver.findElement(By.cssSelector("option:nth-child(8)"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
      }
      Thread.sleep(3000);
      {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = 'Ajuste']")).click();
      }
      Thread.sleep(3000);
    //  driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      {
        WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
      }
      Thread.sleep(3000);
      {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = 'Baixa de Transito - 5x10']")).click();
      }
      Thread.sleep(3000);
    //  driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      {
        WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
      }
      Thread.sleep(3000);
      driver.switchTo().defaultContent();
      driver.findElement(By.id("txtFilial")).click();
      driver.switchTo().frame(1);
      {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = 'ASYST']")).click();
      }
      Thread.sleep(3000);
      //driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      {
        WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
      }
      Thread.sleep(3000);
      driver.switchTo().defaultContent();
      driver.findElement(By.id("txtPrioridade")).click();
      driver.switchTo().frame(1);
      {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = '1 - Crítica']")).click();
      }
      Thread.sleep(3000);
     // driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      {
        WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
      }
      Thread.sleep(3000);
      driver.switchTo().defaultContent();
      driver.findElement(By.id("txtFormaSolicitacao")).click();
      driver.switchTo().frame(1);
      {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = 'E-MAIL']")).click();
      }
      Thread.sleep(3000);
     // driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      {
        WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
      }
      Thread.sleep(3000);
      {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = 'SOLICITAÇÃO']")).click();
      }
      Thread.sleep(3000);
     // driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      {
        WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
      }
      Thread.sleep(3000);
      {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = 'FALHA DE HARDWARE']")).click();
      }
      Thread.sleep(3000);
     // driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      {
        WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
      }
      Thread.sleep(3000);
      driver.switchTo().defaultContent();
      driver.findElement(By.id("txtFormaAtendimento")).click();
      driver.switchTo().frame(1);
      {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = 'PESSOALMENTE']")).click();
      }
      Thread.sleep(3000);
     // driver.findElement(By.cssSelector("option:nth-child(3)")).click();
      driver.findElement(By.cssSelector("option:nth-child(3)")).click();
      {
        WebElement element = driver.findElement(By.cssSelector("option:nth-child(3)"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
      }
      Thread.sleep(3000);
      driver.switchTo().defaultContent();
      driver.findElement(By.id("txtImpacto")).click();
      driver.switchTo().frame(1);
      {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = '1 - Organização']")).click();
      }
      Thread.sleep(3000);
     // driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      {
        WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
      }
      Thread.sleep(3000);
      driver.switchTo().defaultContent();
      driver.findElement(By.id("txtUrgencia")).click();
      driver.switchTo().frame(1);
      {
        WebElement dropdown = driver.findElement(By.id("ListBox1"));
        dropdown.findElement(By.xpath("//option[. = '1 - Crítico']")).click();
      }
      Thread.sleep(3000);
     // driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      driver.findElement(By.cssSelector("option:nth-child(2)")).click();
      {
        WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
      }
      Thread.sleep(3000);
    
    
  }
}
