package TMS;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TMS03Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tMS03() {
    driver.get("http://10.254.16.80/17042019-v2018/Portal/Home");
    driver.get("http://10.254.16.80/17042019-v2018/");
    driver.findElement(By.id("login")).sendKeys("cervello");
    driver.findElement(By.id("senha")).sendKeys("cervello01");
    driver.findElement(By.xpath("//*[@id=\"frmLogin\"]/button")).click();
   // Util.tempo(4);
    driver.findElement(By.xpath("//*[@id=\"frmLogin\"]/button")).click();
driver.manage().window().setSize(new Dimension(1696, 1026));
vars.put("window_handles", driver.getWindowHandles());
 
    driver.findElement(By.cssSelector(".fa-user-headset")).click();
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector(".fancybox-item")).click();
    driver.findElement(By.id("txtUsuario")).click();
    driver.switchTo().frame(1);
    driver.findElement(By.id("txtlogin")).click();
    driver.findElement(By.id("txtlogin")).sendKeys("cervello");
    driver.findElement(By.id("peslogin")).click();
    driver.findElement(By.id("lblSair")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".fancybox-item")).click();
    driver.findElement(By.id("txtProjeto")).click();
    driver.switchTo().frame(1);
    {
      WebElement dropdown = driver.findElement(By.id("ListBox1"));
      dropdown.findElement(By.xpath("//option[. = 'Estoque']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(8)")).click();
    driver.findElement(By.cssSelector("option:nth-child(8)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("option:nth-child(8)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.id("ListBox1"));
      dropdown.findElement(By.xpath("//option[. = 'Ajuste']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.id("ListBox1"));
      dropdown.findElement(By.xpath("//option[. = 'Baixa de Transito - 5x10']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.id("txtFilial")).click();
    driver.switchTo().frame(1);
    {
      WebElement dropdown = driver.findElement(By.id("ListBox1"));
      dropdown.findElement(By.xpath("//option[. = 'ASYST']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.id("txtPrioridade")).click();
    driver.switchTo().frame(1);
    {
      WebElement dropdown = driver.findElement(By.id("ListBox1"));
      dropdown.findElement(By.xpath("//option[. = '1 - Crítica']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.id("txtFormaSolicitacao")).click();
    driver.switchTo().frame(1);
    {
      WebElement dropdown = driver.findElement(By.id("ListBox1"));
      dropdown.findElement(By.xpath("//option[. = 'E-MAIL']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.id("ListBox1"));
      dropdown.findElement(By.xpath("//option[. = 'SOLICITAÇÃO']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.id("ListBox1"));
      dropdown.findElement(By.xpath("//option[. = 'FALHA DE HARDWARE']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.id("txtFormaAtendimento")).click();
    driver.switchTo().frame(1);
    {
      WebElement dropdown = driver.findElement(By.id("ListBox1"));
      dropdown.findElement(By.xpath("//option[. = 'PESSOALMENTE']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(3)")).click();
    driver.findElement(By.cssSelector("option:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("option:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.id("txtImpacto")).click();
    driver.switchTo().frame(1);
    {
      WebElement dropdown = driver.findElement(By.id("ListBox1"));
      dropdown.findElement(By.xpath("//option[. = '1 - Organização']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.id("txtUrgencia")).click();
    driver.switchTo().frame(1);
    {
      WebElement dropdown = driver.findElement(By.id("ListBox1"));
      dropdown.findElement(By.xpath("//option[. = '1 - Crítico']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("option:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.id("txtDescricao")).click();
    driver.findElement(By.id("txtDescricao")).sendKeys("Esta tudo ruim");
    driver.findElement(By.cssSelector("#mnuSalvar > .itemMenu")).click();
    assertThat(driver.switchTo().alert().getText(), is("Deseja salvar o chamado?"));
    driver.switchTo().alert().accept();
    assertThat(driver.switchTo().alert().getText(), is("Os seguintes campos estão inválidos: \nResumo\n"));
    driver.findElement(By.id("txtResumo")).click();
    driver.findElement(By.id("txtResumo")).sendKeys("aaaa");
    driver.findElement(By.cssSelector("#mnuSalvar > .itemMenu")).click();
    assertThat(driver.switchTo().alert().getText(), is("Deseja salvar o chamado?"));
    driver.switchTo().alert().accept();
    assertThat(driver.switchTo().alert().getText(), is("Deseja enviar o e-mail de abertura?"));
    driver.switchTo().alert().dismiss();
  }
}
