package executar;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.gargoylesoftware.htmlunit.javascript.host.file.File;
import com.mongodb.MapReduceCommand.OutputType;
import com.sun.jna.platform.FileUtils;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.TakesScreenshot;

import java.util.*;
public class EditorArtigoV1Test {
  private static WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver","C:\\Users\\10097\\git\\Cervello-Automacao\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

    
  }
  


@After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    @SuppressWarnings("unchecked")
	Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void editorArtigo() throws InterruptedException {
	  driver.get("http://10.254.16.80/17042019-v2018/");
	    driver.findElement(By.id("login")).sendKeys("cervello");
	    driver.findElement(By.id("senha")).sendKeys("cervello01");
	    driver.findElement(By.xpath("//*[@id=\"frmLogin\"]/button")).click();
	   // Util.tempo(4);
	    driver.findElement(By.xpath("//*[@id=\"frmLogin\"]/button")).click();
  driver.manage().window().setSize(new Dimension(1680, 1010));
  vars.put("window_handles", driver.getWindowHandles());
  
  TakesScreenshot scrShot = ((TakesScreenshot) driver);

  
//Seleciona Cards
  driver.findElement(By.xpath("//*[@id=\"portal\"]/main/div[1]/section/div[2]/ul/li[4]/div/a/i")).click();
  Thread.sleep(4000);
  vars.put("win8265", waitForWindow(2000)); 
  driver.switchTo().window(vars.get("win8265").toString());
  Thread.sleep(8000);
  driver.findElement(By.cssSelector(".laptop--18:nth-child(4)")).click();
  Thread.sleep(8000); 
  //Seleciona Artigo
  driver.findElement(By.xpath("//*[@id=\"dvPjaxBs_Render\"]/div/ul/li[1]/div/a")).click();  
    Thread.sleep(8000);
    //Clicar no editar
    driver.findElement(By.xpath("//*[@id=\"dvPjaxBs_Render\"]/div/div[1]/a[1]")).click();
    Thread.sleep(4000);
    //Defini o tipo de topico
    driver.findElement(By.xpath("//option[5]")).click();
      Thread.sleep(4000);
     //(Artigo,Relacionamentos,Permissões)
    driver.findElement(By.xpath("//*[@id=\"tabstrip\"]/ul/li[2]")).click();   
   Thread.sleep(4000);
   
   driver.findElement(By.xpath("//*[@id=\"ddlProjeto\"]/option[5]")).click(); 
   Thread.sleep(4000);
   driver.findElement(By.xpath(" //*[@id=\"ddlTipo\"]/option[1]")).click(); 
   Thread.sleep(4000);
   driver.findElement(By.xpath(" //*[@id=\"ddlAssunto\"]/option[1]")).click(); 
   Thread.sleep(4000);
   driver.findElement(By.xpath(" //*[@id=\"lnkAddAssunto\"]")).click();
   Thread.sleep(4000);
   driver.findElement(By.xpath(" //*[@id=\"ddlTelas\"]/option[4]")).click(); 
   Thread.sleep(4000);
   driver.findElement(By.xpath(" //*[@id=\"lnkAddTela\"]")).click();
   Thread.sleep(4000);
   driver.findElement(By.xpath(" //*[@id=\"btnSalvar\"]")).click(); 
   //(Artigo,Relacionamentos,Permissões)
  driver.findElement(By.xpath("//*[@id=\"tabstrip\"]/ul/li[3]")).click();   
 Thread.sleep(4000);
 driver.findElement(By.xpath("//*[@id=\"tabstrip-3\"]/div[1]/section/div[2]/div/label[1]")).click();

 
  }
}
