// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SssssssTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sssssss() {
    driver.get("http://10.254.16.80/17042019-v2018/Portal/Home");
    driver.manage().window().setSize(new Dimension(1205, 949));
    driver.findElement(By.cssSelector(".fa-user-headset")).click();
    driver.switchTo().frame(0);
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".fancybox-item")).click();
    driver.findElement(By.linkText("Pesquisa")).click();
    driver.findElement(By.cssSelector("li:nth-child(8) li:nth-child(1) .itemMenu")).click();
    driver.switchTo().frame(1);
    driver.findElement(By.id("txtNumeroChamado")).click();
    driver.findElement(By.id("txtNumeroChamado")).sendKeys("300");
    driver.findElement(By.id("pesquisar")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".fancybox-item")).click();
  }
}
