package executar;


// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;


import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import atu.testrecorder.ATUTestRecorder;
import atu.testrecorder.exceptions.ATUTestRecorderException;

import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.TimeUnit;


import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
 
import org.apache.commons.io.FileUtils;
import org.junit.AfterClass;

import org.openqa.selenium.*;

import org.openqa.selenium.Point;

import org.openqa.selenium.internal.WrapsDriver;
import org.openqa.selenium.remote.Augmenter;

import com.lowagie.text.Rectangle;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;

import java.util.UUID;






import java.util.Date;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import org.openqa.selenium.support.ui.Select;

 
public class Teste40Test {
 
    WebDriver driver;
    ATUTestRecorder recorder;
 
    @Before
    public void setUp() throws Exception {
    	
    	System.setProperty("webdriver.chrome.driver","C:\\Users\\10097\\git\\Cervello-Automacao\\chromedriver.exe");
    	
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH-mm-ss");
        Date date = new Date();
 
        //create an object of ATUTestRecorder class and pass 3 parameters explained above.
        recorder = new ATUTestRecorder("C:\\Users\\10097\\git\\Print\\","Script_Video_" + dateFormat.format(date), false);

        //To start video recording.
        recorder.start();
    }
 
    
    
    @Test
    public void testApp() throws InterruptedException {
    	driver = new ChromeDriver();
       // driver.get("http://automate-apps.com/how-to-select-an-option-from-a-drop-down-using-selenium-web-driver/");
        
  	  driver.get("http://10.254.16.80/17042019-v2018/");
  	  driver.manage().window().setSize(new Dimension(1680, 860));
	    driver.findElement(By.id("login")).sendKeys("cervello");
	    driver.findElement(By.id("senha")).sendKeys("cervello01");
	    driver.findElement(By.xpath("//*[@id=\"frmLogin\"]/button")).click();
	   // Util.tempo(4);
	    driver.findElement(By.xpath("//*[@id=\"frmLogin\"]/button")).click();

  
        
        
        driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
                
    }
    
    
 
    @After
    public void tearDown() throws ATUTestRecorderException {
         //close browser
         driver.quit();
        //Stop the recording
          recorder.stop();
    }
 
}